<!-- wp:snow-monkey-blocks/section {"fixedBackgroundColor":"#f4f4f4","contentsAlignment":"left","align":"full","className":"RJE_R002LP_flow is-style-RJE_R002LP_section1"} -->
<div class="wp-block-snow-monkey-blocks-section alignfull smb-section smb-section--left smb-section--fit RJE_R002LP_flow is-style-RJE_R002LP_section1"><div class="smb-section__fixed-background" style="padding-top:0;padding-bottom:0;background-color:#f4f4f4"></div><div class="smb-section__inner"><div class="c-container"><div class="smb-section__subtitle"><meta charset="utf-8">FLOW</div><h2 class="smb-section__title"><meta charset="utf-8">診断から購入までの流れ</h2><div class="smb-section__body"><!-- wp:snow-monkey-blocks/panels {"lg":3,"className":"is-style-RJE_R002LP_flow_panels"} -->
<div class="wp-block-snow-monkey-blocks-panels smb-panels is-style-RJE_R002LP_flow_panels" data-image-padding="false"><div class="c-row c-row--margin c-row--fill" data-columns="1" data-md-columns="1" data-lg-columns="3"><!-- wp:snow-monkey-blocks/panels--item {"imageID":290,"imageSizeSlug":"thumbnail"} -->
<div class="wp-block-snow-monkey-blocks-panels--item c-row__col"><div class="smb-panels__item"><div class="smb-panels__item__figure"><img src="<?php echo esc_url( RJE_R002LP_URL ); ?>dist/img/illust1.png" alt="" width="54" height="95" class="wp-image-290"/></div><div class="smb-panels__item__body"><div class="smb-panels__item__title">診断ページで<br>質問に回答</div><div class="smb-panels__item__content">診断によって、あなたに合うシャンプーをリコメンドします。悩みや好みを教えてください</div></div></div></div>
<!-- /wp:snow-monkey-blocks/panels--item -->

<!-- wp:snow-monkey-blocks/panels--item {"imageID":291,"imageSizeSlug":"thumbnail"} -->
<div class="wp-block-snow-monkey-blocks-panels--item c-row__col"><div class="smb-panels__item"><div class="smb-panels__item__figure"><img src="<?php echo esc_url( RJE_R002LP_URL ); ?>dist/img/illust2.png" alt="" width="92" height="90" class="wp-image-291"/></div><div class="smb-panels__item__body"><div class="smb-panels__item__title">リコメンドされた<br>シャンプーを購入</div><div class="smb-panels__item__content">リコメンドされたシャンプーを、まずは購入して試してみてください</div></div></div></div>
<!-- /wp:snow-monkey-blocks/panels--item -->

<!-- wp:snow-monkey-blocks/panels--item {"imageID":292,"imageSizeSlug":"thumbnail"} -->
<div class="wp-block-snow-monkey-blocks-panels--item c-row__col"><div class="smb-panels__item"><div class="smb-panels__item__figure"><img src="<?php echo esc_url( RJE_R002LP_URL ); ?>dist/img/illust3.png" alt="" width="69" height="89" class="wp-image-292"/></div><div class="smb-panels__item__body"><div class="smb-panels__item__title">ご自宅に<br>シャンプーが届きます</div><div class="smb-panels__item__content">シャンプーが届いたら、早速その日から使って、髪の変化を楽しんでください！</div></div></div></div>
<!-- /wp:snow-monkey-blocks/panels--item --></div></div>
<!-- /wp:snow-monkey-blocks/panels --></div></div></div></div>
<!-- /wp:snow-monkey-blocks/section -->